---
- hosts: all
  tasks: 
  - name: i want to ping
    ping:
  
  - name: iwant to install webserver
    apt:
     name: apache2
     state: present
  
  - name: i want to start webserver on ubuntunodes
    service:
     name: apache2
     state: started