---
- hosts: all
  tasks:
  - name: i want to ping
    ping:

  - name: i want to install apache2
    apt:
     name: apache2
     state: present
    when: ansible_os_family == "Debian"

  - name: i want to start webserver on ubuntu nodes
    service:
     name: apache2
     state: started
    when: ansible_os_family == "Debian"

  
  - name: i want to install webserver on redhat machine
    dnf:
     name: httpd
     state: present
    when: ansible_os_family == "RedHat"

  - name: i want to start webserver on RedHat machine
    service:
     name: hhtpd
     state: started
    when: ansible_os_family == "RedHat"