---
- hosts: webserver
  become: yes
  gather_facts: yes
  tasks:
  - name: i want to ping
    ping:

  - name: i want to install apache2
    apt:
     name: "{{mywebpackonubuntu}}"
     state: present
    when: ansible_os_family == "Debian"

  - name: i want to start webserver on ubuntu nodes
    service:
     name: "{{mywebpackonubuntu}}"
     state: started
    when: ansible_os_family == "Debian"

  
  - name: i want to install webserver on redhat machine
    dnf:
     name: "{{mywebpackonredhat}}"
     state: present
    when: ansible_os_family == "RedHat"

  - name: i want to start webserver on RedHat machine
    service:
     name: "{{mywebpackonredhat}}"
     state: started
    when: ansible_os_family == "RedHat"